In [35]:
import torch
import numpy as np

In [36]:
torch.__version__

'2.9.1+cu126'

## Introduction to tensors

Tensor is a way to represent data in numerical form 

Tensor is an n-dimensional array of numbers 

* Scalar - a single number 
* Vector - a number which have magnitude and direction 
* Matrix - 2D array of numbers

In [37]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [38]:
# ndim will let you know the dimension of the tensor 
scalar.ndim

0

In [39]:
# Get tensor back as python int
scalar.item()

7

In [40]:
#vecotor 

vector = torch.tensor([5,5])
vector

tensor([5, 5])

In [41]:
# vector is 1-dimensional tensor
vector.ndim

1

In [42]:
# Matrix 

matrix = torch.tensor([[7,8],
                      [9,10]])
matrix


tensor([[ 7,  8],
        [ 9, 10]])

In [43]:
# matrix is 2-dimensional tensor
matrix.ndim

2

In [44]:
# This is how we can index into the matrix
matrix[1]

tensor([ 9, 10])

In [45]:
# lets see the shape of the matrix 
matrix.shape

torch.Size([2, 2])

In [46]:
# Tensor

Tensor = torch.tensor([[[1,2,3],
[4,5,6],
[7,8,9]]]) 
Tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [47]:
# Tensor is 3-dimensional tensor
# 1 is the number of samples
# 3 is the number of rows
# 3 is the number of columns
Tensor.shape

torch.Size([1, 3, 3])

In [48]:
Tensor.ndim

3

In [49]:
Tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

##### Tensor can be created from numpy array 

In [50]:
data = [[1,2],[2,3]]
tensor_data = torch.tensor(data)

In [51]:
tensor_data , tensor_data.ndim

(tensor([[1, 2],
         [2, 3]]),
 2)

In [56]:
# from nparray

data_np = np.array(data)
tensor_np = torch.from_numpy(data_np)

In [57]:
tensor_np , tensor_np.ndim

(tensor([[1, 2],
         [2, 3]]),
 2)

##### Tesnor are similar to np array except that tensor can run on gpu's and hardware accelerator
tensor and numpy can share same underlying memory, eliminating the need to copy data 

#### Bridge with numpy

Tensor on the cpu and numpy array can share their underlying memory location , and changing one will change the other

In [60]:
t = torch.ones(5)
print(f"t:{t}")

n = t.numpy()
print(f"n:{n}")

t:tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]


In [61]:
# if i make any changes in the tensor , it will also change in the numpy array

t.add_(1)

tensor([2., 2., 2., 2., 2.])

In [ ]:
print(f"tensor:{t}")
print(f"numpy_array:{n}") 

tensor:tensor([2., 2., 2., 2., 2.])
numpy_array:[2. 2. 2. 2. 2.]


In [64]:
#vice versa 

n = np.ones(5)
t = torch.from_numpy(n)
print(f"t:{t}")
print(f"n:{n}")

# if i make any changes in the numpy array , it will also change in the tensor

n = np.ones(5)
t = torch.from_numpy(n)
print(f"t:{t}")
print(f"n:{n}")




t:tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n:[1. 1. 1. 1. 1.]
t:tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n:[1. 1. 1. 1. 1.]


### Random Tensor

Random tensor - Start with random number 

Why we need random tensor?
In neural network , tesnor start with random numbers because ->

* If all the weights start at zero , neurons would update identically

* Random initialization breaks symmentry so each neuron can learn different patterns

* The distribution matters , to control initial scale 

So basically neural netowork start with random tensor and adujest its value to better represent the data - it is important so the nn will not take any patterns to get better response 

In [52]:
# This will create a random tensor - matrix with random numbers
random_tensor = torch.rand(1,3,4)

In [53]:
random_tensor

tensor([[[0.6608, 0.2085, 0.8479, 0.9317],
         [0.5168, 0.2678, 0.7767, 0.9677],
         [0.9988, 0.6361, 0.8182, 0.6281]]])

In [54]:
random_tensor.size()

torch.Size([1, 3, 4])

#### Representing image in tesnor

In [55]:
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor.shape , random_image_tensor.ndim 

(torch.Size([224, 224, 3]), 3)